name: JustHorse
version: 2.3
api-version: 1.21.3
main: su.spyme.justhorse.Main
description: Horse plugin for Hub server
author: SPY_me
commands:
  justhorse:
    aliases: [horse]
    description: Summon personal horse